#!/usr/bin/env python3
"""Regenerate docs/api.md from the route tables in cli/internal/svc/*."""
import glob
import re

ORDER = ["iam", "cognito", "ec2", "autoscaling", "vpc", "elb", "acm", "s3", "ecr", "ecs", "rds", "lambda", "sqs", "sns", "dynamodb", "events", "sfn", "cfn", "secrets", "kms", "ssm", "cloudwatch", "trail"]
NAMES = {
    "iam": "IAM & authentication", "ec2": "EC2 (compute, volumes, EFS file systems)", "elb": "Elastic Load Balancing",
    "ecr": "ECR (container registry)", "ecs": "ECS (container services)", "kms": "KMS (encryption keys)", "ssm": "Systems Manager Parameter Store", "sfn": "Step Functions", "cognito": "Cognito (user pools)", "autoscaling": "EC2 Auto Scaling", "acm": "Certificate Manager", "cfn": "CloudFormation (stacks)", "vpc": "VPC (networking)", "s3": "S3 (object storage)",
    "rds": "RDS / ElastiCache / DocumentDB (databases)", "lambda": "Lambda & API Gateway (serverless)", "sqs": "SQS (queues)",
    "sns": "SNS (pub/sub)", "dynamodb": "DynamoDB (key-value)", "events": "EventBridge (events & schedules)",
    "secrets": "Secrets Manager", "cloudwatch": "CloudWatch (metrics, logs, alarms)", "trail": "CloudTrail (audit log)",
}
HEADER = """# HomeCloud API reference

<!-- Generated by scripts/gen-api-docs.py from the route tables; do not edit by hand. -->

Every route lives under the server address (default `http://127.0.0.1:8080`). Requests and responses are JSON.

**Authentication.** Send `Authorization: Bearer <token>` where the token is either a console session token from `POST /api/v1/auth/login` or an access key in the form `<access key id>:<secret access key>`. GET requests may pass the token as `?access_token=` instead (used for browser downloads and WebSockets).

**Authorization.** Each route is guarded by the IAM action listed below. Policies can scope actions to resource ARNs such as `arn:hc:s3:::my-bucket` or `arn:hc:ec2:local-1:<account>:instance/i-123`. Path parameters that contain `/` (secret and log group names) must be URL-encoded.

**Errors** look like `{"error": {"code": "ResourceNotFound", "message": "..."}}` with a matching HTTP status.

Public routes (no authentication): `POST /api/v1/auth/login`, `GET /api/v1/health`, function URLs `/lambda-url/{name}/...`, API Gateway endpoints `/apigw/{api}/...`, and static website buckets `/website/{bucket}/...`.
"""

out = [HEADER]
for svc in ORDER:
    rows = []
    for f in sorted(glob.glob(f"cli/internal/svc/{svc}/*.go")):
        if f.endswith("_test.go"):
            continue
        for m in re.finditer(r'r\.Handle\("([A-Z]*) ?([^"]+)", "([^"]*)"', open(f).read()):
            method, path, action = m.groups()
            rows.append((method or "ANY", path, action or "(public)"))
    if rows:
        out += [f"## {NAMES[svc]}", "", "| Method | Path | IAM action |", "|---|---|---|"]
        out += [f"| {m} | `{p}` | `{a}` |" for m, p, a in rows]
        out.append("")
open("docs/api.md", "w").write("\n".join(out))
